### ISSUE TITLE
Microsoft Trademark and Brand Guidelines

### ISSUE THREAD

**Issue by elamalani** [adamfisher/Microsoft.AppCenter.Analytics.Metrics#1]
Hi Adam,
 
I’m a Program Manager at Microsoft working on the App Center team. Thanks for using App Center and creating this [library](https://github.com/adamfisher/Microsoft.AppCenter.Analytics.Metrics) that provides the ability to track additional types of events. We really appreciate your work to build an open source library that extends App Center offering into new scenarios which makes it useful for application developers 👍. Do you plan to add additional metrics to this library? We are very open to community contribution and I’d like to know if we could leverage your help to support it in App Center SDK at some point.
 
Microsoft has set brand [guidelines](https://www.microsoft.com/en-us/legal/intellectualproperty/Trademarks/Usage/General.aspx) for all the trademark products and we are asked to make sure that these are followed when used externally. For the current library, would you mind modifying the library’s name to “Metrics-for-Microsoft-AppCenter-Analytics” (or something similar), and replacing the App Center logo with something else?
 
Thank you for understanding and please let me know if you have any questions.  
 
Regards,
Ela

**Comment by adamfisher** [comment]
Sure thing. I wouldn't mind adding additional metrics to the library but duration was the immediate one I was using right off the bat.

**Comment by elamalani** [comment]
Thanks, @adamfisher :). Please let me know if you have any questions.

**Comment by elamalani** [comment]
@adamfisher I'm following up on this issue. Did you get a chance to modify the library name and replacing the App Center logo on the NuGet?

**Comment by adamfisher** [comment]
I have updated the logo in the latest nuget package but it will not let me change the package name 😕
